apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
        - name: tempo
          image: grafana/tempo:2.5.0
          command: ["/tempo", "--config.file=/etc/tempo/tempo.yaml"]
          ports:
            - containerPort: 3100   # HTTP
            - containerPort: 4317   # OTLP gRPC
          volumeMounts:
            - name: config
              mountPath: /etc/tempo
          readinessProbe:
            httpGet:
              path: /ready
              port: 3100
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /metrics
              port: 3100
            initialDelaySeconds: 30
            periodSeconds: 30
      volumes:
        - name: config
          configMap:
            name: tempo-config