apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
data:
  tempo.yaml: |
    server:
      http_listen_port: 3100

    distributor:
      receivers:
        otlp:
          protocols:
            grpc: {}
            http: {}

    storage:
      trace:
        backend: local
        local:
          path: /tmp/tempo/blocks

    usage_report:
      reporting_enabled: false